# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.26)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS tikicpulib_stubreg tikicpulib_cceprint tikicpulib_npuchk tikicpulib_ascend610 tikicpulib_ascend910 tikicpulib_ascend310p tikicpulib_ascend910B1 tikicpulib_ascend310B1 tikicpulib_ascend610Lite tikicpulib_bs9sx2aa tikicpulib_mc61am21aa)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target tikicpulib_stubreg
add_library(tikicpulib_stubreg SHARED IMPORTED)

# Create imported target tikicpulib_cceprint
add_library(tikicpulib_cceprint SHARED IMPORTED)

# Create imported target tikicpulib_npuchk
add_library(tikicpulib_npuchk SHARED IMPORTED)

# Create imported target tikicpulib_ascend610
add_library(tikicpulib_ascend610 INTERFACE IMPORTED)

set_target_properties(tikicpulib_ascend610 PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<STREQUAL:ascend610,ascend910>:__CCE_AICORE__=100;__DAV_C100__>;\$<\$<STREQUAL:ascend610,ascend610>:__CCE_AICORE__=200;__DAV_M200__>;\$<\$<STREQUAL:ascend610,ascend310p>:__CCE_AICORE__=200;__DAV_M200__>;\$<\$<STREQUAL:ascend610,ascend910B1>:__CCE_AICORE__=220;__DAV_C220__>;\$<\$<STREQUAL:ascend610,ascend310B1>:__CCE_AICORE__=300;__DAV_M300__>;\$<\$<STREQUAL:ascend610,ascend610Lite>:__CCE_AICORE__=310;__DAV_M310__>;\$<\$<STREQUAL:ascend610,bs9sx2aa>:__CCE_AICORE__=310;__DAV_M310__>;\$<\$<STREQUAL:ascend610,mc61am21aa>:__CCE_AICORE__=310;__DAV_M310__>;_GLIBCXX_USE_CXX11_ABI=0;__CCE_KT_TEST__=1;ASCENDC_CPU_DEBUG=1;ASCENDC_DEBUG=1"
  INTERFACE_COMPILE_OPTIONS "-std=c++17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/lib/include;${_IMPORT_PREFIX}/../../include;${_IMPORT_PREFIX}/../../compiler/tikcpp/tikcfw;${_IMPORT_PREFIX}/../../compiler/tikcpp/tikcfw/impl;${_IMPORT_PREFIX}/../../compiler/tikcpp/tikcfw/interface;${_IMPORT_PREFIX}/../../compiler/ascendc/include/highlevel_api/lib/;${_IMPORT_PREFIX}/../../compiler/ascendc/include/highlevel_api/impl/;${_IMPORT_PREFIX}/../../compiler/ascendc/include/highlevel_api/lib/matmul"
  INTERFACE_LINK_DIRECTORIES "${_IMPORT_PREFIX}/lib;${_IMPORT_PREFIX}/lib/Ascend610;${_IMPORT_PREFIX}/../simulator/Ascend610/lib;${_IMPORT_PREFIX}/../../lib64"
  INTERFACE_LINK_LIBRARIES "-Wl,--no-as-needed;c_sec;\$<\$<STREQUAL:ascend610,ascend910>:-l_pvmodel>;\$<\$<STREQUAL:ascend610,ascend610>:-l_pvmodel>;\$<\$<STREQUAL:ascend610,ascend310p>:-l_pvmodel>;\$<\$<STREQUAL:ascend610,ascend910B1>:-lpem_davinci>;\$<\$<STREQUAL:ascend610,ascend310B1>:-lpem_davinci>;\$<\$<STREQUAL:ascend610,ascend610Lite>:-lpem_davinci>;\$<\$<STREQUAL:ascend610,bs9sx2aa>:-lpem_davinci>;\$<\$<STREQUAL:ascend610,mc61am21aa>:-lpem_davinci>;-ltikcpp_debug;tikicpulib_stubreg;tikicpulib_cceprint;tikicpulib_npuchk;-Wl,--as-needed"
)

# Create imported target tikicpulib_ascend910
add_library(tikicpulib_ascend910 INTERFACE IMPORTED)

set_target_properties(tikicpulib_ascend910 PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<STREQUAL:ascend910,ascend910>:__CCE_AICORE__=100;__DAV_C100__>;\$<\$<STREQUAL:ascend910,ascend610>:__CCE_AICORE__=200;__DAV_M200__>;\$<\$<STREQUAL:ascend910,ascend310p>:__CCE_AICORE__=200;__DAV_M200__>;\$<\$<STREQUAL:ascend910,ascend910B1>:__CCE_AICORE__=220;__DAV_C220__>;\$<\$<STREQUAL:ascend910,ascend310B1>:__CCE_AICORE__=300;__DAV_M300__>;\$<\$<STREQUAL:ascend910,ascend610Lite>:__CCE_AICORE__=310;__DAV_M310__>;\$<\$<STREQUAL:ascend910,bs9sx2aa>:__CCE_AICORE__=310;__DAV_M310__>;\$<\$<STREQUAL:ascend910,mc61am21aa>:__CCE_AICORE__=310;__DAV_M310__>;_GLIBCXX_USE_CXX11_ABI=0;__CCE_KT_TEST__=1;ASCENDC_CPU_DEBUG=1;ASCENDC_DEBUG=1"
  INTERFACE_COMPILE_OPTIONS "-std=c++17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/lib/include;${_IMPORT_PREFIX}/../../include;${_IMPORT_PREFIX}/../../compiler/tikcpp/tikcfw;${_IMPORT_PREFIX}/../../compiler/tikcpp/tikcfw/impl;${_IMPORT_PREFIX}/../../compiler/tikcpp/tikcfw/interface;${_IMPORT_PREFIX}/../../compiler/ascendc/include/highlevel_api/lib/;${_IMPORT_PREFIX}/../../compiler/ascendc/include/highlevel_api/impl/;${_IMPORT_PREFIX}/../../compiler/ascendc/include/highlevel_api/lib/matmul"
  INTERFACE_LINK_DIRECTORIES "${_IMPORT_PREFIX}/lib;${_IMPORT_PREFIX}/lib/Ascend910A;${_IMPORT_PREFIX}/../simulator/Ascend910A/lib;${_IMPORT_PREFIX}/../../lib64"
  INTERFACE_LINK_LIBRARIES "-Wl,--no-as-needed;c_sec;\$<\$<STREQUAL:ascend910,ascend910>:-l_pvmodel>;\$<\$<STREQUAL:ascend910,ascend610>:-l_pvmodel>;\$<\$<STREQUAL:ascend910,ascend310p>:-l_pvmodel>;\$<\$<STREQUAL:ascend910,ascend910B1>:-lpem_davinci>;\$<\$<STREQUAL:ascend910,ascend310B1>:-lpem_davinci>;\$<\$<STREQUAL:ascend910,ascend610Lite>:-lpem_davinci>;\$<\$<STREQUAL:ascend910,bs9sx2aa>:-lpem_davinci>;\$<\$<STREQUAL:ascend910,mc61am21aa>:-lpem_davinci>;-ltikcpp_debug;tikicpulib_stubreg;tikicpulib_cceprint;tikicpulib_npuchk;-Wl,--as-needed"
)

# Create imported target tikicpulib_ascend310p
add_library(tikicpulib_ascend310p INTERFACE IMPORTED)

set_target_properties(tikicpulib_ascend310p PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<STREQUAL:ascend310p,ascend910>:__CCE_AICORE__=100;__DAV_C100__>;\$<\$<STREQUAL:ascend310p,ascend610>:__CCE_AICORE__=200;__DAV_M200__>;\$<\$<STREQUAL:ascend310p,ascend310p>:__CCE_AICORE__=200;__DAV_M200__>;\$<\$<STREQUAL:ascend310p,ascend910B1>:__CCE_AICORE__=220;__DAV_C220__>;\$<\$<STREQUAL:ascend310p,ascend310B1>:__CCE_AICORE__=300;__DAV_M300__>;\$<\$<STREQUAL:ascend310p,ascend610Lite>:__CCE_AICORE__=310;__DAV_M310__>;\$<\$<STREQUAL:ascend310p,bs9sx2aa>:__CCE_AICORE__=310;__DAV_M310__>;\$<\$<STREQUAL:ascend310p,mc61am21aa>:__CCE_AICORE__=310;__DAV_M310__>;_GLIBCXX_USE_CXX11_ABI=0;__CCE_KT_TEST__=1;ASCENDC_CPU_DEBUG=1;ASCENDC_DEBUG=1"
  INTERFACE_COMPILE_OPTIONS "-std=c++17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/lib/include;${_IMPORT_PREFIX}/../../include;${_IMPORT_PREFIX}/../../compiler/tikcpp/tikcfw;${_IMPORT_PREFIX}/../../compiler/tikcpp/tikcfw/impl;${_IMPORT_PREFIX}/../../compiler/tikcpp/tikcfw/interface;${_IMPORT_PREFIX}/../../compiler/ascendc/include/highlevel_api/lib/;${_IMPORT_PREFIX}/../../compiler/ascendc/include/highlevel_api/impl/;${_IMPORT_PREFIX}/../../compiler/ascendc/include/highlevel_api/lib/matmul"
  INTERFACE_LINK_DIRECTORIES "${_IMPORT_PREFIX}/lib;${_IMPORT_PREFIX}/lib/Ascend310P1;${_IMPORT_PREFIX}/../simulator/Ascend310P1/lib;${_IMPORT_PREFIX}/../../lib64"
  INTERFACE_LINK_LIBRARIES "-Wl,--no-as-needed;c_sec;\$<\$<STREQUAL:ascend310p,ascend910>:-l_pvmodel>;\$<\$<STREQUAL:ascend310p,ascend610>:-l_pvmodel>;\$<\$<STREQUAL:ascend310p,ascend310p>:-l_pvmodel>;\$<\$<STREQUAL:ascend310p,ascend910B1>:-lpem_davinci>;\$<\$<STREQUAL:ascend310p,ascend310B1>:-lpem_davinci>;\$<\$<STREQUAL:ascend310p,ascend610Lite>:-lpem_davinci>;\$<\$<STREQUAL:ascend310p,bs9sx2aa>:-lpem_davinci>;\$<\$<STREQUAL:ascend310p,mc61am21aa>:-lpem_davinci>;-ltikcpp_debug;tikicpulib_stubreg;tikicpulib_cceprint;tikicpulib_npuchk;-Wl,--as-needed"
)

# Create imported target tikicpulib_ascend910B1
add_library(tikicpulib_ascend910B1 INTERFACE IMPORTED)

set_target_properties(tikicpulib_ascend910B1 PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<STREQUAL:ascend910B1,ascend910>:__CCE_AICORE__=100;__DAV_C100__>;\$<\$<STREQUAL:ascend910B1,ascend610>:__CCE_AICORE__=200;__DAV_M200__>;\$<\$<STREQUAL:ascend910B1,ascend310p>:__CCE_AICORE__=200;__DAV_M200__>;\$<\$<STREQUAL:ascend910B1,ascend910B1>:__CCE_AICORE__=220;__DAV_C220__>;\$<\$<STREQUAL:ascend910B1,ascend310B1>:__CCE_AICORE__=300;__DAV_M300__>;\$<\$<STREQUAL:ascend910B1,ascend610Lite>:__CCE_AICORE__=310;__DAV_M310__>;\$<\$<STREQUAL:ascend910B1,bs9sx2aa>:__CCE_AICORE__=310;__DAV_M310__>;\$<\$<STREQUAL:ascend910B1,mc61am21aa>:__CCE_AICORE__=310;__DAV_M310__>;_GLIBCXX_USE_CXX11_ABI=0;__CCE_KT_TEST__=1;ASCENDC_CPU_DEBUG=1;ASCENDC_DEBUG=1"
  INTERFACE_COMPILE_OPTIONS "-std=c++17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/lib/include;${_IMPORT_PREFIX}/../../include;${_IMPORT_PREFIX}/../../compiler/tikcpp/tikcfw;${_IMPORT_PREFIX}/../../compiler/tikcpp/tikcfw/impl;${_IMPORT_PREFIX}/../../compiler/tikcpp/tikcfw/interface;${_IMPORT_PREFIX}/../../compiler/ascendc/include/highlevel_api/lib/;${_IMPORT_PREFIX}/../../compiler/ascendc/include/highlevel_api/impl/;${_IMPORT_PREFIX}/../../compiler/ascendc/include/highlevel_api/lib/matmul"
  INTERFACE_LINK_DIRECTORIES "${_IMPORT_PREFIX}/lib;${_IMPORT_PREFIX}/lib/Ascend910B1;${_IMPORT_PREFIX}/../simulator/Ascend910B1/lib;${_IMPORT_PREFIX}/../../lib64"
  INTERFACE_LINK_LIBRARIES "-Wl,--no-as-needed;c_sec;\$<\$<STREQUAL:ascend910B1,ascend910>:-l_pvmodel>;\$<\$<STREQUAL:ascend910B1,ascend610>:-l_pvmodel>;\$<\$<STREQUAL:ascend910B1,ascend310p>:-l_pvmodel>;\$<\$<STREQUAL:ascend910B1,ascend910B1>:-lpem_davinci>;\$<\$<STREQUAL:ascend910B1,ascend310B1>:-lpem_davinci>;\$<\$<STREQUAL:ascend910B1,ascend610Lite>:-lpem_davinci>;\$<\$<STREQUAL:ascend910B1,bs9sx2aa>:-lpem_davinci>;\$<\$<STREQUAL:ascend910B1,mc61am21aa>:-lpem_davinci>;-ltikcpp_debug;tikicpulib_stubreg;tikicpulib_cceprint;tikicpulib_npuchk;-Wl,--as-needed"
)

# Create imported target tikicpulib_ascend310B1
add_library(tikicpulib_ascend310B1 INTERFACE IMPORTED)

set_target_properties(tikicpulib_ascend310B1 PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<STREQUAL:ascend310B1,ascend910>:__CCE_AICORE__=100;__DAV_C100__>;\$<\$<STREQUAL:ascend310B1,ascend610>:__CCE_AICORE__=200;__DAV_M200__>;\$<\$<STREQUAL:ascend310B1,ascend310p>:__CCE_AICORE__=200;__DAV_M200__>;\$<\$<STREQUAL:ascend310B1,ascend910B1>:__CCE_AICORE__=220;__DAV_C220__>;\$<\$<STREQUAL:ascend310B1,ascend310B1>:__CCE_AICORE__=300;__DAV_M300__>;\$<\$<STREQUAL:ascend310B1,ascend610Lite>:__CCE_AICORE__=310;__DAV_M310__>;\$<\$<STREQUAL:ascend310B1,bs9sx2aa>:__CCE_AICORE__=310;__DAV_M310__>;\$<\$<STREQUAL:ascend310B1,mc61am21aa>:__CCE_AICORE__=310;__DAV_M310__>;_GLIBCXX_USE_CXX11_ABI=0;__CCE_KT_TEST__=1;ASCENDC_CPU_DEBUG=1;ASCENDC_DEBUG=1"
  INTERFACE_COMPILE_OPTIONS "-std=c++17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/lib/include;${_IMPORT_PREFIX}/../../include;${_IMPORT_PREFIX}/../../compiler/tikcpp/tikcfw;${_IMPORT_PREFIX}/../../compiler/tikcpp/tikcfw/impl;${_IMPORT_PREFIX}/../../compiler/tikcpp/tikcfw/interface;${_IMPORT_PREFIX}/../../compiler/ascendc/include/highlevel_api/lib/;${_IMPORT_PREFIX}/../../compiler/ascendc/include/highlevel_api/impl/;${_IMPORT_PREFIX}/../../compiler/ascendc/include/highlevel_api/lib/matmul"
  INTERFACE_LINK_DIRECTORIES "${_IMPORT_PREFIX}/lib;${_IMPORT_PREFIX}/lib/Ascend310B1;${_IMPORT_PREFIX}/../simulator/Ascend310B1/lib;${_IMPORT_PREFIX}/../../lib64"
  INTERFACE_LINK_LIBRARIES "-Wl,--no-as-needed;c_sec;\$<\$<STREQUAL:ascend310B1,ascend910>:-l_pvmodel>;\$<\$<STREQUAL:ascend310B1,ascend610>:-l_pvmodel>;\$<\$<STREQUAL:ascend310B1,ascend310p>:-l_pvmodel>;\$<\$<STREQUAL:ascend310B1,ascend910B1>:-lpem_davinci>;\$<\$<STREQUAL:ascend310B1,ascend310B1>:-lpem_davinci>;\$<\$<STREQUAL:ascend310B1,ascend610Lite>:-lpem_davinci>;\$<\$<STREQUAL:ascend310B1,bs9sx2aa>:-lpem_davinci>;\$<\$<STREQUAL:ascend310B1,mc61am21aa>:-lpem_davinci>;-ltikcpp_debug;tikicpulib_stubreg;tikicpulib_cceprint;tikicpulib_npuchk;-Wl,--as-needed"
)

# Create imported target tikicpulib_ascend610Lite
add_library(tikicpulib_ascend610Lite INTERFACE IMPORTED)

set_target_properties(tikicpulib_ascend610Lite PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<STREQUAL:ascend610Lite,ascend910>:__CCE_AICORE__=100;__DAV_C100__>;\$<\$<STREQUAL:ascend610Lite,ascend610>:__CCE_AICORE__=200;__DAV_M200__>;\$<\$<STREQUAL:ascend610Lite,ascend310p>:__CCE_AICORE__=200;__DAV_M200__>;\$<\$<STREQUAL:ascend610Lite,ascend910B1>:__CCE_AICORE__=220;__DAV_C220__>;\$<\$<STREQUAL:ascend610Lite,ascend310B1>:__CCE_AICORE__=300;__DAV_M300__>;\$<\$<STREQUAL:ascend610Lite,ascend610Lite>:__CCE_AICORE__=310;__DAV_M310__>;\$<\$<STREQUAL:ascend610Lite,bs9sx2aa>:__CCE_AICORE__=310;__DAV_M310__>;\$<\$<STREQUAL:ascend610Lite,mc61am21aa>:__CCE_AICORE__=310;__DAV_M310__>;_GLIBCXX_USE_CXX11_ABI=0;__CCE_KT_TEST__=1;ASCENDC_CPU_DEBUG=1;ASCENDC_DEBUG=1"
  INTERFACE_COMPILE_OPTIONS "-std=c++17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/lib/include;${_IMPORT_PREFIX}/../../include;${_IMPORT_PREFIX}/../../compiler/tikcpp/tikcfw;${_IMPORT_PREFIX}/../../compiler/tikcpp/tikcfw/impl;${_IMPORT_PREFIX}/../../compiler/tikcpp/tikcfw/interface;${_IMPORT_PREFIX}/../../compiler/ascendc/include/highlevel_api/lib/;${_IMPORT_PREFIX}/../../compiler/ascendc/include/highlevel_api/impl/;${_IMPORT_PREFIX}/../../compiler/ascendc/include/highlevel_api/lib/matmul"
  INTERFACE_LINK_DIRECTORIES "${_IMPORT_PREFIX}/lib;${_IMPORT_PREFIX}/lib/Ascend610Lite;${_IMPORT_PREFIX}/../simulator/Ascend610Lite/lib;${_IMPORT_PREFIX}/../../lib64"
  INTERFACE_LINK_LIBRARIES "-Wl,--no-as-needed;c_sec;\$<\$<STREQUAL:ascend610Lite,ascend910>:-l_pvmodel>;\$<\$<STREQUAL:ascend610Lite,ascend610>:-l_pvmodel>;\$<\$<STREQUAL:ascend610Lite,ascend310p>:-l_pvmodel>;\$<\$<STREQUAL:ascend610Lite,ascend910B1>:-lpem_davinci>;\$<\$<STREQUAL:ascend610Lite,ascend310B1>:-lpem_davinci>;\$<\$<STREQUAL:ascend610Lite,ascend610Lite>:-lpem_davinci>;\$<\$<STREQUAL:ascend610Lite,bs9sx2aa>:-lpem_davinci>;\$<\$<STREQUAL:ascend610Lite,mc61am21aa>:-lpem_davinci>;-ltikcpp_debug;tikicpulib_stubreg;tikicpulib_cceprint;tikicpulib_npuchk;-Wl,--as-needed"
)

# Create imported target tikicpulib_bs9sx2aa
add_library(tikicpulib_bs9sx2aa INTERFACE IMPORTED)

set_target_properties(tikicpulib_bs9sx2aa PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<STREQUAL:bs9sx2aa,ascend910>:__CCE_AICORE__=100;__DAV_C100__>;\$<\$<STREQUAL:bs9sx2aa,ascend610>:__CCE_AICORE__=200;__DAV_M200__>;\$<\$<STREQUAL:bs9sx2aa,ascend310p>:__CCE_AICORE__=200;__DAV_M200__>;\$<\$<STREQUAL:bs9sx2aa,ascend910B1>:__CCE_AICORE__=220;__DAV_C220__>;\$<\$<STREQUAL:bs9sx2aa,ascend310B1>:__CCE_AICORE__=300;__DAV_M300__>;\$<\$<STREQUAL:bs9sx2aa,ascend610Lite>:__CCE_AICORE__=310;__DAV_M310__>;\$<\$<STREQUAL:bs9sx2aa,bs9sx2aa>:__CCE_AICORE__=310;__DAV_M310__>;\$<\$<STREQUAL:bs9sx2aa,mc61am21aa>:__CCE_AICORE__=310;__DAV_M310__>;_GLIBCXX_USE_CXX11_ABI=0;__CCE_KT_TEST__=1;ASCENDC_CPU_DEBUG=1;ASCENDC_DEBUG=1"
  INTERFACE_COMPILE_OPTIONS "-std=c++17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/lib/include;${_IMPORT_PREFIX}/../../include;${_IMPORT_PREFIX}/../../compiler/tikcpp/tikcfw;${_IMPORT_PREFIX}/../../compiler/tikcpp/tikcfw/impl;${_IMPORT_PREFIX}/../../compiler/tikcpp/tikcfw/interface;${_IMPORT_PREFIX}/../../compiler/ascendc/include/highlevel_api/lib/;${_IMPORT_PREFIX}/../../compiler/ascendc/include/highlevel_api/impl/;${_IMPORT_PREFIX}/../../compiler/ascendc/include/highlevel_api/lib/matmul"
  INTERFACE_LINK_DIRECTORIES "${_IMPORT_PREFIX}/lib;${_IMPORT_PREFIX}/lib/BS9SX2AA;${_IMPORT_PREFIX}/../simulator/BS9SX2AA/lib;${_IMPORT_PREFIX}/../../lib64"
  INTERFACE_LINK_LIBRARIES "-Wl,--no-as-needed;c_sec;\$<\$<STREQUAL:bs9sx2aa,ascend910>:-l_pvmodel>;\$<\$<STREQUAL:bs9sx2aa,ascend610>:-l_pvmodel>;\$<\$<STREQUAL:bs9sx2aa,ascend310p>:-l_pvmodel>;\$<\$<STREQUAL:bs9sx2aa,ascend910B1>:-lpem_davinci>;\$<\$<STREQUAL:bs9sx2aa,ascend310B1>:-lpem_davinci>;\$<\$<STREQUAL:bs9sx2aa,ascend610Lite>:-lpem_davinci>;\$<\$<STREQUAL:bs9sx2aa,bs9sx2aa>:-lpem_davinci>;\$<\$<STREQUAL:bs9sx2aa,mc61am21aa>:-lpem_davinci>;-ltikcpp_debug;tikicpulib_stubreg;tikicpulib_cceprint;tikicpulib_npuchk;-Wl,--as-needed"
)

# Create imported target tikicpulib_mc61am21aa
add_library(tikicpulib_mc61am21aa INTERFACE IMPORTED)

set_target_properties(tikicpulib_mc61am21aa PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<STREQUAL:mc61am21aa,ascend910>:__CCE_AICORE__=100;__DAV_C100__>;\$<\$<STREQUAL:mc61am21aa,ascend610>:__CCE_AICORE__=200;__DAV_M200__>;\$<\$<STREQUAL:mc61am21aa,ascend310p>:__CCE_AICORE__=200;__DAV_M200__>;\$<\$<STREQUAL:mc61am21aa,ascend910B1>:__CCE_AICORE__=220;__DAV_C220__>;\$<\$<STREQUAL:mc61am21aa,ascend310B1>:__CCE_AICORE__=300;__DAV_M300__>;\$<\$<STREQUAL:mc61am21aa,ascend610Lite>:__CCE_AICORE__=310;__DAV_M310__>;\$<\$<STREQUAL:mc61am21aa,bs9sx2aa>:__CCE_AICORE__=310;__DAV_M310__>;\$<\$<STREQUAL:mc61am21aa,mc61am21aa>:__CCE_AICORE__=310;__DAV_M310__>;_GLIBCXX_USE_CXX11_ABI=0;__CCE_KT_TEST__=1;ASCENDC_CPU_DEBUG=1;ASCENDC_DEBUG=1"
  INTERFACE_COMPILE_OPTIONS "-std=c++17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/lib/include;${_IMPORT_PREFIX}/../../include;${_IMPORT_PREFIX}/../../compiler/tikcpp/tikcfw;${_IMPORT_PREFIX}/../../compiler/tikcpp/tikcfw/impl;${_IMPORT_PREFIX}/../../compiler/tikcpp/tikcfw/interface;${_IMPORT_PREFIX}/../../compiler/ascendc/include/highlevel_api/lib/;${_IMPORT_PREFIX}/../../compiler/ascendc/include/highlevel_api/impl/;${_IMPORT_PREFIX}/../../compiler/ascendc/include/highlevel_api/lib/matmul"
  INTERFACE_LINK_DIRECTORIES "${_IMPORT_PREFIX}/lib;${_IMPORT_PREFIX}/lib/MC61AM21AA;${_IMPORT_PREFIX}/../simulator/MC61AM21AA/lib;${_IMPORT_PREFIX}/../../lib64"
  INTERFACE_LINK_LIBRARIES "-Wl,--no-as-needed;c_sec;\$<\$<STREQUAL:mc61am21aa,ascend910>:-l_pvmodel>;\$<\$<STREQUAL:mc61am21aa,ascend610>:-l_pvmodel>;\$<\$<STREQUAL:mc61am21aa,ascend310p>:-l_pvmodel>;\$<\$<STREQUAL:mc61am21aa,ascend910B1>:-lpem_davinci>;\$<\$<STREQUAL:mc61am21aa,ascend310B1>:-lpem_davinci>;\$<\$<STREQUAL:mc61am21aa,ascend610Lite>:-lpem_davinci>;\$<\$<STREQUAL:mc61am21aa,bs9sx2aa>:-lpem_davinci>;\$<\$<STREQUAL:mc61am21aa,mc61am21aa>:-lpem_davinci>;-ltikcpp_debug;tikicpulib_stubreg;tikicpulib_cceprint;tikicpulib_npuchk;-Wl,--as-needed"
)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/targets-tikicpulib-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
    if(NOT EXISTS "${_cmake_file}")
      message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
